## Importing the Libraries

In [64]:
import pandas as pd
import numpy as np

## Loading the dataset

In [65]:
data = pd.read_csv(r'raw.csv')
data.head()

,age,experience_years,daily_work_hours,sleep_hours,caffeine_intake,bugs_per_day,commits_per_day,meetings_per_day,screen_time,exercise_hours,stress_level,burnout_level
0,26.0,12.0,10.33,4.45,2.0,11.0,4.0,1.0,15.07,0.14,55.96,Medium
1,39.0,10.0,8.62,5.77,5.0,15.0,11.0,5.0,13.25,0.54,82.22,High
2,34.0,13.0,NaN,4.03,5.0,2.0,18.0,9.0,11.18,1.54,61.77,Medium
3,30.0,1.0,6.85,6.47,2.0,15.0,26.0,1.0,11.14,0.96,54.98,Medium
4,27.0,7.0,4.24,5.80,NaN,9.0,17.0,7.0,8.05,0.36,27.90,Low

## Extracting the basic values

In [66]:
data.isnull().sum()

age                 140
experience_years    140
daily_work_hours    140
sleep_hours         140
caffeine_intake     140
bugs_per_day        140
commits_per_day     140
meetings_per_day    140
screen_time         140
exercise_hours      140
stress_level        140
burnout_level       140
dtype: int64

In [67]:
data.shape

(7000, 12)

In [68]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7000 entries, 0 to 6999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   age               6860 non-null   float64
 1   experience_years  6860 non-null   float64
 2   daily_work_hours  6860 non-null   float64
 3   sleep_hours       6860 non-null   float64
 4   caffeine_intake   6860 non-null   float64
 5   bugs_per_day      6860 non-null   float64
 6   commits_per_day   6860 non-null   float64
 7   meetings_per_day  6860 non-null   float64
 8   screen_time       6860 non-null   float64
 9   exercise_hours    6860 non-null   float64
 10  stress_level      6860 non-null   float64
 11  burnout_level     6860 non-null   object
dtypes: float64(11), object(1)
memory usage: 656.4+ KB

In [69]:
data.columns

Index(['age', 'experience_years', 'daily_work_hours', 'sleep_hours',
       'caffeine_intake', 'bugs_per_day', 'commits_per_day',
       'meetings_per_day', 'screen_time', 'exercise_hours', 'stress_level',
       'burnout_level'],
      dtype='object')

In [70]:
data.describe()

,age,experience_years,daily_work_hours,sleep_hours,caffeine_intake,bugs_per_day,commits_per_day,meetings_per_day,screen_time,exercise_hours,stress_level
count,6860.000000,6860.000000,6860.000000,6860.000000,6860.000000,6860.000000,6860.000000,6860.000000,6860.000000,6860.000000,6860.000000
mean,32.129446,9.581050,9.000277,6.485638,3.540671,9.482653,14.458455,4.545044,11.974773,1.007611,53.652825
std,7.230254,5.760972,2.863944,1.445008,2.283445,5.751664,8.669846,2.856766,3.091204,0.576708,23.446656
min,20.000000,0.000000,4.000000,4.000000,0.000000,0.000000,0.000000,0.000000,5.210000,0.000000,0.000000
25%,26.000000,5.000000,6.560000,5.220000,2.000000,5.000000,7.000000,2.000000,9.460000,0.510000,36.587500
50%,32.000000,10.000000,8.990000,6.460000,4.000000,9.000000,14.000000,5.000000,12.020000,1.020000,53.795000
75%,38.000000,15.000000,11.422500,7.740000,6.000000,14.000000,22.000000,7.000000,14.422500,1.510000,70.800000
max,44.000000,19.000000,14.000000,9.000000,7.000000,19.000000,29.000000,9.000000,18.930000,2.000000,100.000000

## Working with null columns

In [71]:
columns = ["age","experience_years","daily_work_hours","sleep_hours",
           "caffeine_intake","bugs_per_day","screen_time","meetings_per_day","commits_per_day","exercise_hours","stress_level"]

for i in range(len(columns)):
    col = columns[i]
    data[col] = data[col].replace("null", pd.NA)
    data[col] = data[col].fillna(data[col].median())

In [72]:
data["screen_time"] = data["screen_time"].replace(0, data["screen_time"].median())

In [73]:
data["burnout_level"] = data["burnout_level"].replace("<null>", pd.NA)
data["burnout_level"] = data["burnout_level"].fillna(data["burnout_level"].mode()[0])

In [74]:
data.isnull().sum()

age                 0
experience_years    0
daily_work_hours    0
sleep_hours         0
caffeine_intake     0
bugs_per_day        0
commits_per_day     0
meetings_per_day    0
screen_time         0
exercise_hours      0
stress_level        0
burnout_level       0
dtype: int64

## Correcting the datatype

In [75]:
data.head()
columns = ["age","experience_years","caffeine_intake","bugs_per_day","meetings_per_day","commits_per_day","stress_level"]

for i in range(len(columns)):
    col = columns[i]
    data[col] = data[col].astype(np.int32)

In [76]:
data.dtypes

age                   int32
experience_years      int32
daily_work_hours    float64
sleep_hours         float64
caffeine_intake       int32
bugs_per_day          int32
commits_per_day       int32
meetings_per_day      int32
screen_time         float64
exercise_hours      float64
stress_level          int32
burnout_level        object
dtype: object

In [77]:
data.head()

,age,experience_years,daily_work_hours,sleep_hours,caffeine_intake,bugs_per_day,commits_per_day,meetings_per_day,screen_time,exercise_hours,stress_level,burnout_level
0,26,12,10.33,4.45,2,11,4,1,15.07,0.14,55,Medium
1,39,10,8.62,5.77,5,15,11,5,13.25,0.54,82,High
2,34,13,8.99,4.03,5,2,18,9,11.18,1.54,61,Medium
3,30,1,6.85,6.47,2,15,26,1,11.14,0.96,54,Medium
4,27,7,4.24,5.80,4,9,17,7,8.05,0.36,27,Low

## Correcting column names

In [78]:
data.columns = data.columns.str.capitalize()

In [79]:
data.head()

,Age,Experience_years,Daily_work_hours,Sleep_hours,Caffeine_intake,Bugs_per_day,Commits_per_day,Meetings_per_day,Screen_time,Exercise_hours,Stress_level,Burnout_level
0,26,12,10.33,4.45,2,11,4,1,15.07,0.14,55,Medium
1,39,10,8.62,5.77,5,15,11,5,13.25,0.54,82,High
2,34,13,8.99,4.03,5,2,18,9,11.18,1.54,61,Medium
3,30,1,6.85,6.47,2,15,26,1,11.14,0.96,54,Medium
4,27,7,4.24,5.80,4,9,17,7,8.05,0.36,27,Low

## Age Group Column Addition

In [80]:
def aging(x):
    if x <= 25:
        return "20-25"
    elif x <= 30:
        return "26-30"
    elif x <= 35:
        return "31-35"
    elif x <= 40:
        return "36-40"
    else:
        return "41-45"

data["Age_Group"] = data["Age"].apply(aging)

In [81]:
data.head()

,Age,Experience_years,Daily_work_hours,Sleep_hours,Caffeine_intake,Bugs_per_day,Commits_per_day,Meetings_per_day,Screen_time,Exercise_hours,Stress_level,Burnout_level,Age_Group
0,26,12,10.33,4.45,2,11,4,1,15.07,0.14,55,Medium,26-30
1,39,10,8.62,5.77,5,15,11,5,13.25,0.54,82,High,36-40
2,34,13,8.99,4.03,5,2,18,9,11.18,1.54,61,Medium,31-35
3,30,1,6.85,6.47,2,15,26,1,11.14,0.96,54,Medium,26-30
4,27,7,4.24,5.80,4,9,17,7,8.05,0.36,27,Low,26-30

## Saving the file

In [82]:
data.to_csv('Final.csv', index=False)